apiVersion: v2
appVersion: "1.0"
version: 1.2.3
name: enterprise-locations-packages
description: Official Gatling Enterprise Helm chart for Private Locations & Packages
home: https://gatling.io
icon: https://helm.gatling.io/gatling.png
maintainers:
  - name: "Thomas Petillot"
    email: "tpetillot@gatling.io"
sources:
  - "https://github.com/gatling/helm-control-plane"
keywords:
  - load-testing
  - smoke-testing
  - stress-testing
  - capacity-testing
  - soak-testing
  - distributed-testing
  - kubernetes
